name: "Fetch resources and deploy every 2 hours"

#on:
#  push:
#    branches: [main]
on:
  schedule:
  - cron: "0 */2 * * *"

env:
  GITHUB_ACCESS_TOKEN: ${{secrets.ACCESS_TOKEN}}
  GITHUB_USERNAME: ${{secrets.USERNAME}}

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.14.0]
    steps:
    - uses: actions/checkout@v3

    - name: use node.js ${{matrix.node-version}}
      uses: actions/setup-node@v1
      with:
        node-version: ${{matrix.node-version}}

    - run: yarn

    - run: yarn build:all

    - name: 'gcp auth'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: ${{secrets.GCP_CREDENTIALS_JSON}}

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v0'

    - name: 'Upload Site'
      run: 'gsutil -m -h "Cache-Control:private, max-age=0, no-transform" rsync -d -r ./build gs://neovimcraft.com'

    - name: 'upload-file'
      uses: 'google-github-actions/upload-cloud-storage@v0'
      with:
        path: './src/lib/db.json'
        destination: 'neovimcraft.com/db.json'
        parent: false
        headers: |-
          cache-control: private, max-age=0, no-transform

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v4
